# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#Cool same reasons i love programming, cs in General
<<<<i want to commit to it that was the reason i ask the question>>>>>
i love the creativity aspect..... having the power to create something from scratch that never existed before (feel like having a super hero strength)solving problems
just wanted to know how to commit to it and know it more deeper...
thanks....


On Mon, Jan 20, 2020 at 3:50 AM Yasuhiro MATSUMOTO <mattn.jp@gmail.com> wrote:
Sorry I won't have good advice to you. I'm just a person who love programming. I love:

* Solving problems with programming
* Surprise people with programming
* Makes everyone happy with program i wrote

mattn
On Mon, Jan 20, 2020 at 3:27 PM Adejumo David Adewale <the.daveads@gmail.com> wrote:
how do i get good with programming?
i know you are the right person for this.... with your verse knowledge in different languages and i kind of have a thing for every languages....
your advice will be deeply appreciated sir


-- 
- Yasuhiro Matsumoto
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
q# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Daveads
email: the.daveads@gmail.com
description: Daveads personal site
baseurl: "" # the subpath of your site, e.g. /blog

url: "https://daveads.github.io"

twitter_username: The_Daveads
github_username:  Daveads

logo: "/images/daveads.png"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

url: https://daveads.github.io # the base hostname & protocol for your site

css_class: 'highlight'

google_analytics: UA-150099529-1

lang_direction: "ltr"

color: "#abe123"

language: "en"

disqus:

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#

exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
